version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: container_mysql_2
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33060:3306
  api:
    container_name: api_2
    image: node:16
    restart: always
    ports:
      - 30010:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=orm_trybe
      - DB_USER=root
      - DB_PASSWORD=password
      - SERVER_PORT=30010
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql