version: '3'
services:
  frontend:
    build: frontend/
    ports:
      - 3000:3000
  backend:
    build: backend/
    ports:
      - 3001:3001
  database:
    image: betrybe/docker-compose-example-database:v1