version: '3'

services:
  db:
    container_name: aula-tabelas
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306