version: '3'

services:
  db:
    container_name: mentoria-01-compose
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3308:3306